version: 0.0
os: linux
files:
  - source: /
    destination: /home/openkm/apache-tomcat-8.5.51/webapps/
hooks:
  ApplicationStop:
    - location: scripts/stop_ser
      timeout: 300
  ApplicationStart:
    - location: scripts/start_ser
      timeout: 300

