---
- hosts: all
  become: yes
  tasks:
    - name: update hosts file
      blockinfile:
        path: /etc/hosts
        block: |
         172.31.46.250 lb01
         172.31.45.171 app01
         172.31.41.86 mq01
         172.31.32.119 mc01
         172.31.34.16 db01
